# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Auto devops."
  homepage "https://outblocks.io"
  version "0.1.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/outblocks/outblocks-cli/releases/download/v0.1.0/outblocks-0.1.0-darwin_amd64.tar.gz"
      sha256 "0d486fa1176e1b729bfd020fd332212adfaf2b32455061cdf9e22ae6a6b52ce4"
    end
    if Hardware::CPU.arm?
      url "https://github.com/outblocks/outblocks-cli/releases/download/v0.1.0/outblocks-0.1.0-darwin_arm64.tar.gz"
      sha256 "c0cc06d29d14b6bfbd5b2f1487613616de146e5fa4aa3d7021a5fc829941d9c8"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/outblocks/outblocks-cli/releases/download/v0.1.0/outblocks-0.1.0-linux_amd64.tar.gz"
      sha256 "15ade596a2cb5b25d4843b7ff515bdd050199feaf0cc35d1aaaad30c99f6dc4f"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/outblocks/outblocks-cli/releases/download/v0.1.0/outblocks-0.1.0-linux_armv6.tar.gz"
      sha256 "ce16dccd7f75df8332e30b95f1280e68ae3293196cb015e8efc560e45e875363"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/outblocks/outblocks-cli/releases/download/v0.1.0/outblocks-0.1.0-linux_arm64.tar.gz"
      sha256 "bf812e26182980e1bf9b49dc7cefba1836d91c649dbe2260a6d26d3448af6aa2"
    end
  end

  depends_on "git"

  def install
    bin.install "ok"
    output = Utils.popen_read("#{bin}/ok completion bash")
    (bash_completion/"ok").write output
    output = Utils.popen_read("#{bin}/ok completion zsh")
    (zsh_completion/"_ok").write output
    output = Utils.popen_read("#{bin}/ok completion fish")
    (fish_completion/"eksctl.fish").write output
    prefix.install_metafiles
  end

  test do
    system "#{bin}/ok --version"
  end
end
